# Generated by Django 6.0.5 on 2026-07-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='match_score',
            field=models.FloatField(default=0.0, help_text='Cosine similarity score from chaotic allocation algorithm (0–1)'),
        ),
    ]
